service: movies

provider:
    name: aws
    runtime: python3.8
    stage: ${opt:stage, 'dev'}
    region: us-east-1
    lambdaHashingVersion: 20201221
    
functions:
    get_movie:
        name: get_movie_${self:provider.stage}
        handler: lambda_get_movie.handler
